// app/layout.js
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider, CssBaseline } from '@mui/material';
import theme from './theme';
import './globals.css';
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

export const metadata = {
  title: 'MUI + Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
            <NavBar />
            {children}
            <Footer />
        </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
      </html>
  );
}